# This is a basic workflow to help you get started with Actions

name: remote ssh command

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      CI: false

    steps:
      - uses: actions/checkout@v2
      
      - uses: appleboy/ssh-action@master
        name: executing remote ssh commands using password
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd CKMC_CLIENT
            git fetch --all 
            git reset --hard main
            git pull origin main
            npm install
            npm run build
